# The class cannot be named by Pascal or camel case.
# The class cannot be named by Pascal or camel case.
# If it is not used, the corresponding structure will not be set,
# and it will not be read naturally.
#---------------Infrastructure configuration---------------------#
sdk_version: 1.0.0
sdk_data_dir: ./
etcd:
  etcdSchema: wallet  #默认即可
  etcdAddr: [ etcd:2379 ] #单机部署时，默认即可

#Skip init all database, set it true when u need to run the ethgrpc unit test, otherwise set it false
is_skip_database: true

#main database
mysql:
  dbMysqlAddress: [ mysql:3306 ] #mysql地址 目前仅支持单机，默认即可
  dbMysqlUserName: root #mysql用户名，建议修改
  dbMysqlPassword: 123456 # mysql密码，建议修改
  dbMysqlDatabaseName: wallet #默认即可
  dbMaxOpenConns: 2000
  dbMaxIdleConns: 1000
  dbMaxLifeTime: 120

#store admin logs and transaction records
mongo:
  dbUri: ""#当dbUri值不为空则直接使用该值
  dbAddress: mongo:27017  #单机时为mongo地址，使用分片集群时，为mongos地址 默认即可
  dbDirect: false
  dbTimeout: 60
  dbDatabase: wallet  #mongo db 默认即可
  dbSource: admin
  dbUserName: worker  #mongo用户名，建议先不设置
  dbPassword: 123456  #mongo密码，建议先不设置
  dbMaxPoolSize: 100

#store jwt token and any cache
redis:
  dbAddress: [ redis:6379 ] #redis地址 单机时，填写一个地址即可，使用redis集群时候，填写集群中多个节点地址（主从地址都可以填写，增加容灾能力），默认即可
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbPassWord: 123456 #redis密码 建议修改
  enableCluster: false #如果外部redis以集群方式启动，需要打开此开关

#---------------Internal service configuration---------------------#
# RPC
rpcRegisterIP: 0.0.0.0
listenIP: 0.0.0.0

wallet_api:
  walletApiPort: [ 20001 ] #api服务端口，默认即可，需要开放此端口或做nginx转发
  listenIP: 0.0.0.0

admin_api:
  adminApiPort: [ 20002 ] #管理后台api服务端口，默认即可，需要开放此端口或做nginx转发
  listenIP: 0.0.0.0

rpc_port: #rpc服务端口 默认即可
  walletRPCPort: [ 20100]
  adminRPCPort: [ 20120 ]
  btcRPCPort: [ 20130 ]
  ethRPCPort: [ 20140 ]
  trxRPCPort: [ 20150 ]

rpc_register_name: #rpc注册服务名，默认即可
  walletRPCName: wallet_rpc
  adminRPCName: admin_rpc
  btcRPCName: btc_rpc
  ethRPCName: eth_rpc
  trxRPCName: trx_rpc

log:
  storageLocation: ../logs/
  rotationTime: 24
  remainRotationCount: 3 #日志数量
  #日志级别 0 panic 1 fetal 2 error 3 warn 4 info 5 debug 6 trace 6表示全都打印，测试阶段建议设置为6
  remainLogLevel: 6
  #gorm loglevel 1 slient 2 error 3 warn 4 info
  gormLogLevel: 3
  elasticSearchSwitch: false
  elasticSearchAddr: [ 127.0.0.1:9201 ]
  elasticSearchUser: ""
  elasticSearchPassword: ""

## 推送只能开启一个 enable代表开启
push:
  jpns: #极光推送 在极光后台申请后，修改以下四项，必须修改
    appKey: dec43f9061c1f5fe4ddf4dfb
    masterSecret: 197fda75cd363b409306bd7c
    pushUrl: "https://api.jpush.cn/v3/push"
    pushIntent: "intent:#Intent;component=io.zoom.app/io.zoom.app.MainActivity;end"
    enable: true

#token config for admin
tokenpolicy:
  accessSecret: "wallet_server" #token生成相关，默认即可
  accessSecretGAuth: "wallet_google_auth"
  # Token effective time day as a unit
  accessExpire: 30 #token过期时间（天） 默认即可

#admin switch
adminUser2FAuthEnable : true

#swagger switch, if false will unable to access the swagger url
swaggerEable: true

#minimum block number for confirmation, if (latest_block_number - tx_block_number) >= minimum number, update the transaction to complete state
minimumBlockNumber: 10

manager:
  #app管理员userID和对应的secret  建议修改。 用于管理后台登录，也可以用户管理后台对应的api
  appManagerUid: [ "wallet001","wallet002", "wallet003", "wallet004","spswadmin"]
  secrets: [ "a001678@!","a002jkl@!", "a003fgh@!", "a004poi@!","spws01gt@!"]
  actions : [
    {name : "All" , pid : 0},
    {name : "Home page" , pid : 1},
    {name : "Statistical statement" , pid : 1},
    {name : "Account management" , pid : 1},
    {name : "Financial management",pid : 1},
    {name : "Currency management" , pid : 1},
    {name : "Administrator management", pid : 1},
    {name : "Operational report" , pid: 3},
    {name : "Account management", pid : 4},
    {name : "Receive detail" ,pid : 5},
    {name : "Transfer detail" ,pid : 5},
    {name : "Funds log", pid : 5},
    {name : "Export EXCEL receive detail", pid : 10},
    {name : "Export EXCEL transfer detail", pid: 11},
    {name : "Export EXCEL funds log", pid: 12},
    {name : "Wallet currencies", pid: 6},
    {name : "Edit state", pid: 16},
    {name : "Role management", pid: 7},
    {name : "Administrator list", pid: 7},
    {name : "Add/Edit administrator", pid: 19},
    {name : "Delete admin", pid: 19},
    {name : "Set/Reset Google Verification Code", pid: 19},
    {name : "Add/Edit role", pid: 18},
    {name : "Delete role", pid: 18},
    {name : "Export EXCEL operational report", pid: 8},
    {name : "Export EXCEL account management", pid: 9}
  ]